### PR TITLE
Add GitHub Action to lint and test Python code

### PR DESCRIPTION
**Pull request by cclauss**
Test results: https://github.com/cclauss/baduk-id/actions
% `pytest`
```
============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.3.1, pluggy-1.0.0
rootdir: /home/runner/work/baduk-id/baduk-id
collected 7 items

tests/test_baduk_id.py .......                                           [100%]

============================== 7 passed in 0.23s ===============================
```

### CODE REVIEW

**Comment by benjaminpjones** [comment]
Great idea! Thanks!

This is the first time I've heard of ruff - without a config file, is it actually checking anything?

**Review by benjaminpjones — APPROVED** [review]

**Comment by cclauss** [comment]
https://beta.ruff.rs/docs/configuration says:
> If left unspecified, Ruff's default configuration is equivalent to:

**Comment by cclauss** [comment]
Some rules should really be ignored but with `--select=ALL`...

% `ruff --select=ALL --statistics --target-version=py37 . | sort -k 2`
```
 3	A001  	[ ] Variable `id` is shadowing a python builtin
 3	A002  	[ ] Argument `id` is shadowing a python builtin
15	ANN001	[ ] Missing type annotation for function argument `board`
 7	ANN101	[ ] Missing type annotation for `self` in method
16	ANN201	[ ] Missing return type annotation for public function `C`
 2	D100  	[ ] Missing docstring in public module
 2	D101  	[ ] Missing docstring in public class
 7	D102  	[ ] Missing docstring in public method
 9	D103  	[ ] Missing docstring in public function
 2	D104  	[ ] Missing docstring in public package
 1	EM102 	[ ] Exception must not use an f-string literal, assign to variable first
 7	ERA001	[*] Found commented-out code
 1	I001  	[*] Import block is un-sorted or un-formatted
 1	N802  	[ ] Function name `C` should be lowercase
 9	PT009 	[*] Use a regular `assert` instead of unittest-style `assertEqual`
 1	TRY003	[ ] Avoid specifying long messages outside the exception class
 1	W293  	[*] Blank line contains whitespace
```
Also try `ruff --ALL --ignore=ERA001 --fix .` to see what that does.

**Comment by benjaminpjones** [comment]
Oh cool, I was kind of surprised it passed without changes, but the ALL output makes sense.  I'll take a look!

**Pull request merged**
